# Exercises (Unordered)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## PCA

### Exercise 7

In [21]:
X = np.array([
    [167, 1, 163, 23, 41, 8, 6, 6],
    [162, 2, 141, 12, 40, 12, 4, 15],
    [119, 6, 69, 56, 39, 5, 13, 41],
    [87, 11, 63, 111, 27, 3, 18, 39],
    [103, 5, 68, 77, 32, 4, 11, 30],
    [111, 4, 72, 66, 34, 6, 10, 28],
    [130, 3, 76, 52, 43, 7, 7, 16],
    [138, 7, 117, 74, 53, 8, 12, 20]
])

col_names = ["bread_ord", "bread_oth", "wine_ord", "wine_oth", "potatoes", "veg", "grapes", "dishes"]

df = pd.DataFrame(X, columns=col_names)
df

   bread_ord  bread_oth  wine_ord  wine_oth  potatoes  veg  grapes  dishes
0        167          1       163        23        41    8       6       6
1        162          2       141        12        40   12       4      15
2        119          6        69        56        39    5      13      41
3         87         11        63       111        27    3      18      39
4        103          5        68        77        32    4      11      30
5        111          4        72        66        34    6      10      28
6        130          3        76        52        43    7       7      16
7        138          7       117        74        53    8      12      20

In [22]:
# First Part 
x_bar_vec = X.mean(axis=0)
Y = X - x_bar_vec

std_vec = X.std(axis=0)
D_inv = np.diag(1/std_vec)

Z = Y @ D_inv
Z

array([[ 1.5276103 , -1.30187763,  1.84304239, -1.22467425,  0.32249746,
         0.52028215, -0.9900495 , -1.60399697],
       [ 1.33606042, -0.96590921,  1.23673312, -1.60018412,  0.18670905,
         2.03383021, -1.47007351, -0.8183658 ],
       [-0.31126856,  0.37796447, -0.74755177, -0.09814463,  0.05092065,
        -0.6148789 ,  0.6900345 ,  1.45123536],
       [-1.53718779,  2.05780658, -0.91290885,  1.77940475, -1.57854018,
        -1.37165293,  1.89009451,  1.27665065],
       [-0.92422818,  0.04199605, -0.77511128,  0.61873786, -0.89959817,
        -0.99326592,  0.2100105 ,  0.49101948],
       [-0.61774837, -0.29397237, -0.66487323,  0.24322799, -0.62802136,
        -0.23649188, -0.0300015 ,  0.31643478],
       [ 0.11014118, -0.62994079, -0.55463519, -0.23469367,  0.59407426,
         0.14189513, -0.7500375 , -0.73107345],
       [ 0.41662099,  0.71393289,  0.57530482,  0.51632608,  1.95195829,
         0.52028215,  0.4500225 , -0.38190404]])

In [23]:
# Second Part
S = np.cov(X, rowvar=False, bias=True)

R = D_inv @ S @ D_inv
R

array([[ 1.        , -0.77366429,  0.92618779, -0.90579293,  0.65635246,
         0.88855935, -0.83342732, -0.85584573],
       [-0.77366429,  1.        , -0.60401329,  0.90444147, -0.33288793,
        -0.673371  ,  0.95881782,  0.77122091],
       [ 0.92618779, -0.60401329,  1.        , -0.7501607 ,  0.51707538,
         0.79172558, -0.66900616, -0.82798621],
       [-0.90579293,  0.90444147, -0.7501607 ,  1.        , -0.41856612,
        -0.83860212,  0.9239285 ,  0.71979081],
       [ 0.65635246, -0.33288793,  0.51707538, -0.41856612,  1.        ,
         0.60291886, -0.40993174, -0.55395606],
       [ 0.88855935, -0.673371  ,  0.79172558, -0.83860212,  0.60291886,
         1.        , -0.82445193, -0.75092306],
       [-0.83342732,  0.95881782, -0.66900616,  0.9239285 , -0.40993174,
        -0.82445193,  1.        ,  0.8344475 ],
       [-0.85584573,  0.77122091, -0.82798621,  0.71979081, -0.55395606,
        -0.75092306,  0.8344475 ,  1.        ]])

In [24]:
# Third Part
v, U = np.linalg.eig(R)
v

array([ 6.20794684e+00,  8.79681393e-01,  4.15961123e-01,  3.06454670e-01,
        1.68441497e-01,  1.80677086e-02, -1.65178045e-17,  3.44676890e-03])

In [46]:
col_with_eig = pd.Series({col_name: eig for col_name, eig in zip(col_names, v)})
col_with_eig.sort_values(ascending=False, inplace=True)

df_summary = pd.DataFrame(col_with_eig, columns=["eigenvalue"])
df_summary["cumsum"] = df_summary.cumsum()
total_sum = df_summary["cumsum"].max()
df_summary["cumulative_percentage"] = df_summary["cumsum"] / total_sum
df_summary

             eigenvalue    cumsum  cumulative_percentage
bread_ord  6.207947e+00  6.207947               0.775993
bread_oth  8.796814e-01  7.087628               0.885954
wine_ord   4.159611e-01  7.503589               0.937949
wine_oth   3.064547e-01  7.810044               0.976256
potatoes   1.684415e-01  7.978486               0.997311
veg        1.806771e-02  7.996553               0.999569
dishes     3.446769e-03  8.000000               1.000000
grapes    -1.651780e-17  8.000000               1.000000

In [49]:
C = Z @ U[:, :2]
C

array([[ 3.37157878, -0.24581608],
       [ 3.52171174, -0.4473986 ],
       [-1.47203093,  0.05851415],
       [-4.35878646,  0.17610682],
       [-1.71807772, -0.85664744],
       [-0.80653462, -0.80852679],
       [ 0.89910009, -0.18303912],
       [ 0.56303911,  2.30680707]])